dices: [0, 4, 6, 8, 10, 12, 20, 100]
humanSize: 3
diceSuccess: 10
attackTypes:
  - contact
  - ranged
dammageTypes:
  - cutting
  - blunt
  - piercing
powerTypes:
  - material
  - fire
  - ice
  - electricity
  - acid
  - magic